<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CameraVision.Core\CameraVision.Core.csproj" />
    <ProjectReference Include="..\CameraVision.Infrastructure\CameraVision.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" />
  </ItemGroup>

</Project>
