// <auto-generated />
using System;
using CameraVision.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CameraVision.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903041744_RuleNotifications")]
    partial class RuleNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("CameraVision.Core.Entities.AdminAlertSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Emails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyEmail")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyRecovery")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyWhatsApp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WhatsAppNumbers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkerDownAfterSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AdminAlertSettings");
                });

            modelBuilder.Entity("CameraVision.Core.Entities.AlertDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaptureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaptureRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContactId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Recipient")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CaptureId");

                    b.HasIndex("ContactId");

                    b.HasIndex("TenantId");

                    b.HasIndex("CaptureRuleId", "SentAt");

                    b.HasIndex("Status", "QueuedAt");

                    b.ToTable("AlertDeliveries");
                });

            modelBuilder.Entity("CameraVision.Core.Entities.AlertSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Channel")
                        .IsUnique();

                    b.ToTable("AlertSettings");
                });

            modelBuilder.Entity("CameraVision.Core.Entities.AlertTrigger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<int>("CaptureRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Days")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CaptureRuleId");

                    b.ToTable("AlertTriggers");
                });

            modelBuilder.Entity("CameraVision.Core.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CameraVision.Core.Entities.Camera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredStream")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessorStatus")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessorStatusAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreamUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubStreamUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("CameraVision.Core.Entities.CameraHealthEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CameraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CameraName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DigestedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Suppressed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("TenantId");

                    b.HasIndex("CameraId", "OccurredAt");

                    b.ToTable("CameraHealthEvents");
                });

            modelBuilder.Entity("CameraVision.Core.Entities.Capture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CameraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CameraName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IndexedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMerged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectClass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("CameraName");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.HasIndex("ObjectClass");

                    b.HasIndex("StartedAt");

                    b.HasIndex("TenantId");

                    b.ToTable("Captures");
                });

            modelBuilder.Entity("CameraVision.Core.Entities.CaptureRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("ActiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("ActiveTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ConfidenceThreshold")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupWindowMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LingerSeconds")
                        .HasColumnType("REAL");

                    b.Property<int>("MaxSegmentSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("CaptureRules");
                });

            modelBuilder.Entity("CameraVision.Core.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyCameraHealth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WhatsAppNumber")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("CameraVision.Core.Entities.HealthAlertSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveChecks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DigestEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DigestIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FloodCapCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FloodCapWindowMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastDigestAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyEmail")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyRecovery")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyWhatsApp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeakLatencyMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("HealthAlertSettings");
                });

            modelBuilder.Entity("CameraVision.Core.Entities.SystemAlertEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detail")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.ToTable("SystemAlertEvents");
                });

            modelBuilder.Entity("CameraVision.Core.Entities.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvolutionApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvolutionBaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvolutionInstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicBaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpSecurity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpSenderEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpSenderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("CameraVision.Core.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("CameraVision.Core.Entities.WorkerStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveCameras")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Device")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastHeartbeatAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkerStatus");
                });

            modelBuilder.Entity("CameraVision.Core.Entities.AlertDelivery", b =>
                {
                    b.HasOne("CameraVision.Core.Entities.Capture", null)
                        .WithMany()
                        .HasForeignKey("CaptureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CameraVision.Core.Entities.CaptureRule", null)
                        .WithMany()
                        .HasForeignKey("CaptureRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CameraVision.Core.Entities.Contact", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CameraVision.Core.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CameraVision.Core.Entities.AlertSettings", b =>
                {
                    b.HasOne("CameraVision.Core.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CameraVision.Core.Entities.AlertTrigger", b =>
                {
                    b.HasOne("CameraVision.Core.Entities.CaptureRule", null)
                        .WithMany("Triggers")
                        .HasForeignKey("CaptureRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CameraVision.Core.Entities.AppUser", b =>
                {
                    b.HasOne("CameraVision.Core.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CameraVision.Core.Entities.Camera", b =>
                {
                    b.HasOne("CameraVision.Core.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CameraVision.Core.Entities.CameraHealthEvent", b =>
                {
                    b.HasOne("CameraVision.Core.Entities.Camera", null)
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CameraVision.Core.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CameraVision.Core.Entities.Capture", b =>
                {
                    b.HasOne("CameraVision.Core.Entities.Camera", null)
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CameraVision.Core.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CameraVision.Core.Entities.CaptureRule", b =>
                {
                    b.HasOne("CameraVision.Core.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CameraVision.Core.Entities.Contact", b =>
                {
                    b.HasOne("CameraVision.Core.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CameraVision.Core.Entities.CaptureRule", b =>
                {
                    b.Navigation("Triggers");
                });
#pragma warning restore 612, 618
        }
    }
}
